### ISSUE TITLE
opencv Error

### ISSUE THREAD

**Issue by Tarasus** [gigafide/simple_opencv_pi_face_detector#2]
File "face_tracker_usb.py", line 25, in <module>
    flags=cv2.cv.CV_HAAR_SCALE_IMAGE
AttributeError: module 'cv2.cv2' has no attribute 'cv'

Python 3.6.5 [GCC 7.3.0]
Lubuntu on Ubuntu 18.04 LTS

**Comment by Tarasus** [comment]
Checked it out on Python 2.7.15rc1 [GCC 7.3.0] 
Got the same error message.

**Comment by gigafide** [comment]
You're using a newer version of OpenCV than I was using. In newer versions, you don't need the extra ".cv" in that line, so it should just be
"cv2.CV_HAAR_SCALE_IMAGE"

reference: https://stackoverflow.com/questions/33177376/what-is-the-cv2-cv-replacement-in-opencv3

**Comment by Tarasus** [comment]
Thank you!
